### PR TITLE
Refactor python imports (#353)

### PR DESCRIPTION
**Pull request by FrankXenarthra**
Lack of order in imports leads to duplicates and makes it harder to understand thecode.

The issue only refereced two files but with the isort utility every python file has been modified automatically.

### CODE REVIEW

**Comment by denisvmedyantsev** [comment]
@FrankXenarthra Thanks for your PR.

We use [black](https://github.com/psf/black) in the project (https://github.com/insight-platform/Savant/blob/develop/Makefile#L131) and the new multi-line import format does not satisfy their rules. The multi-line import format needs to be corrected.

What tool did you use to fix the imports? We need a tool to manually reformat imports via make (like black).

**Comment by bwsw** [comment]
@FrankXenarthra @denisvmedyantsev looks like isort supports black:

https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

**Comment by FrankXenarthra** [comment]
@bwsw @denisvmedyantsev I would create a new PR including an .isort.cfg with black profile and apply isort then for the commit. Do you agree? Is it the correct approach to always create a new PR in case I ammended a commit? Thanks for the clarification!

**Comment by bwsw** [comment]
@FrankXenarthra add a commit right to the current PR, no need creating new PR.

**Comment by denisvmedyantsev** [comment]
I missed the mention of isort. @bwsw, you are right, we only need the section in the pyproject.toml file
```
[tool.isort]
profile = "black"
```
Then relaunch isort.

**Comment by denisvmedyantsev** [comment]
@FrankXenarthra, one more thing. Please, add isort to `requirements/dev.txt` and commands check/run-isort in the `Makefile`.

**Comment by FrankXenarthra** [comment]
@bwsw @denisvmedyantsev I implemented the propose changes. Couldn't you have a look please?

**Review by denisvmedyantsev — APPROVED** [review]

**Pull request merged**
